version: "3"
services:
  post_note:
    image: debian
    entrypoint: /bin/create
    environment:
      - GRID=sandbox
      - PORT=80
      - DBHOST=mysql
      - DBUSER=root
      - DBPW=password
      - DBNAME=pingpen
    ports:
      - "4000:80"
    networks:
      - webnet
    volumes:
      - ./api/bin:/bin
    depends_on:
      - "mysql"
                 
  mysql:
    image: mysql:5.6
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=pingpen
    ports:
      - "3306:3306"
    networks:
      - webnet
    volumes:
      - ./db/fixtures:/docker-entrypoint-initdb.d
    healthcheck:
      test: 'mysqladmin -uroot -ppassword ping'
      interval: 10s
      timeout: 2s
      retries: 10



networks:
  webnet:

