// Code generated by protoc-gen-go. DO NOT EDIT.
// source: service.proto

/*
Package pb is a generated protocol buffer package.

It is generated from these files:
	service.proto

It has these top-level messages:
	AddRequest
	SubRequest
	MathResponse
*/
package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type AddRequest struct {
	NumOne int64 `protobuf:"varint,1,opt,name=num_one,json=numOne" json:"num_one,omitempty"`
	NumTwo int64 `protobuf:"varint,2,opt,name=num_two,json=numTwo" json:"num_two,omitempty"`
}

func (m *AddRequest) Reset()                    { *m = AddRequest{} }
func (m *AddRequest) String() string            { return proto.CompactTextString(m) }
func (*AddRequest) ProtoMessage()               {}
func (*AddRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *AddRequest) GetNumOne() int64 {
	if m != nil {
		return m.NumOne
	}
	return 0
}

func (m *AddRequest) GetNumTwo() int64 {
	if m != nil {
		return m.NumTwo
	}
	return 0
}

type SubRequest struct {
	NumOne int64 `protobuf:"varint,1,opt,name=num_one,json=numOne" json:"num_one,omitempty"`
	NumTwo int64 `protobuf:"varint,2,opt,name=num_two,json=numTwo" json:"num_two,omitempty"`
}

func (m *SubRequest) Reset()                    { *m = SubRequest{} }
func (m *SubRequest) String() string            { return proto.CompactTextString(m) }
func (*SubRequest) ProtoMessage()               {}
func (*SubRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *SubRequest) GetNumOne() int64 {
	if m != nil {
		return m.NumOne
	}
	return 0
}

func (m *SubRequest) GetNumTwo() int64 {
	if m != nil {
		return m.NumTwo
	}
	return 0
}

type MathResponse struct {
	Sum int64 `protobuf:"varint,1,opt,name=sum" json:"sum,omitempty"`
}

func (m *MathResponse) Reset()                    { *m = MathResponse{} }
func (m *MathResponse) String() string            { return proto.CompactTextString(m) }
func (*MathResponse) ProtoMessage()               {}
func (*MathResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *MathResponse) GetSum() int64 {
	if m != nil {
		return m.Sum
	}
	return 0
}

func init() {
	proto.RegisterType((*AddRequest)(nil), "pb.AddRequest")
	proto.RegisterType((*SubRequest)(nil), "pb.SubRequest")
	proto.RegisterType((*MathResponse)(nil), "pb.MathResponse")
}

func init() { proto.RegisterFile("service.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 176 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2d, 0x4e, 0x2d, 0x2a,
	0xcb, 0x4c, 0x4e, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2a, 0x48, 0x52, 0xb2, 0xe3,
	0xe2, 0x72, 0x4c, 0x49, 0x09, 0x4a, 0x2d, 0x2c, 0x4d, 0x2d, 0x2e, 0x11, 0x12, 0xe7, 0x62, 0xcf,
	0x2b, 0xcd, 0x8d, 0xcf, 0xcf, 0x4b, 0x95, 0x60, 0x54, 0x60, 0xd4, 0x60, 0x0e, 0x62, 0xcb, 0x2b,
	0xcd, 0xf5, 0xcf, 0x4b, 0x85, 0x49, 0x94, 0x94, 0xe7, 0x4b, 0x30, 0xc1, 0x25, 0x42, 0xca, 0xf3,
	0x41, 0xfa, 0x83, 0x4b, 0x93, 0xc8, 0xd7, 0xaf, 0xc0, 0xc5, 0xe3, 0x9b, 0x58, 0x92, 0x11, 0x94,
	0x5a, 0x5c, 0x90, 0x9f, 0x57, 0x9c, 0x2a, 0x24, 0xc0, 0xc5, 0x5c, 0x5c, 0x9a, 0x0b, 0xd5, 0x0d,
	0x62, 0x1a, 0x25, 0x72, 0x71, 0xfa, 0x56, 0x06, 0x43, 0x1c, 0x2e, 0xa4, 0xc9, 0xc5, 0xec, 0x98,
	0x92, 0x22, 0xc4, 0xa7, 0x57, 0x90, 0xa4, 0x87, 0x70, 0xb7, 0x94, 0x00, 0x88, 0x8f, 0x6c, 0x8e,
	0x12, 0x03, 0x48, 0x69, 0x70, 0x69, 0x12, 0x44, 0x29, 0xc2, 0x89, 0xd8, 0x94, 0x26, 0xb1, 0x81,
	0xc3, 0xc3, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0x2b, 0xa4, 0x36, 0xd7, 0x20, 0x01, 0x00, 0x00,
}
